In [9]:
# import pandas 
import pandas as pd 

file = r'C:\Users\saarah.rasheed\Downloads\archive\Car_sales.csv'

data = pd.read_csv(file)

In [10]:
data.head()

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639

In [11]:
data.shape

(157, 16)

In [16]:
data.isna().any()

Manufacturer           False
Model                  False
Sales_in_thousands     False
__year_resale_value     True
Vehicle_type           False
Price_in_thousands      True
Engine_size             True
Horsepower              True
Wheelbase               True
Width                   True
Length                  True
Curb_weight             True
Fuel_capacity           True
Fuel_efficiency         True
Latest_Launch          False
Power_perf_factor       True
dtype: bool

In [22]:
column_name = '__year_resale_value'
# column_name = 'Price_in_thousands'
subset = data[column_name].isna()
# data[subset.isna()]
data[subset]
# to see number of obs where row is nan
# data[subset].shape

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
7,BMW,323i,19.747,NaN,Passenger,26.990,2.5,170.0,107.3,68.4,176.0,3.179,16.6,26.0,6/28/2011,71.191207
18,Cadillac,Escalade,14.785,NaN,Car,46.225,5.7,255.0,117.5,77.0,201.2,5.572,30.0,15.0,4/17/2012,109.509117
27,Chevrolet,Impala,107.995,NaN,Passenger,18.890,3.4,180.0,110.5,73.0,200.0,3.389,17.0,27.0,6/18/2011,71.838039
34,Chrysler,300M,30.696,NaN,Passenger,29.185,3.5,253.0,113.0,74.4,197.8,3.567,17.0,23.0,2/10/2012,101.655244
44,Dodge,Durango,101.323,NaN,Car,26.310,5.2,230.0,115.7,71.7,193.5,4.394,25.0,17.0,6/27/2012,92.854125
50,Ford,Focus,175.670,NaN,Passenger,12.315,2.0,107.0,103.0,66.9,174.8,2.564,13.2,30.0,7/22/2012,43.117132
66,Jaguar,S-Type,15.467,NaN,Passenger,42.800,3.0,240.0,114.5,71.6,191.3,3.650,18.4,21.0,11/3/2012,102.178985
72,Lexus,GS400,3.334,NaN,Passenger,46.305,4.0,300.0,110.2,70.9,189.2,3.693,19.8,21.0,11/28/2012,125.013357
74,Lexus,LX470,9.126,NaN,Car,60.105,4.7,230.0,112.2,76.4,192.5,5.401,25.4,15.0,10/30/2012,105.760458
75,Lexus,RX300,51.238,NaN,Car,34.605,3.0,220.0,103.0,71.5,180.1,3.900,17.2,21.0,1/4/2012,91.943802
78,Lincoln,Navigator,22.925,NaN,Car,42.660,5.4,300.0,119.0,79.9,204.8,5.393,30.0,15.0,12/23/2012,123.972047
96,Mercedes-B,SLK,7.998,NaN,Passenger,38.900,2.3,190.0,94.5,67.5,157.9,3.055,15.9,26.0,1/16/2011,82.807362
97,Mercedes-B,SLK230,1.526,NaN,Passenger,41.000,2.3,185.0,94.5,67.5,157.3,2.975,14.0,27.0,8/6/2011,81.848969
98,Mercedes-B,CLK Coupe,11.592,NaN,Passenger,41.600,3.2,215.0,105.9,67.8,180.3,3.213,16.4,26.0,7/8/2011,92.925792
99,Mercedes-B,CL500,0.954,NaN,Passenger,85.500,5.0,302.0,113.6,73.1,196.6,4.115,23.2,20.0,4/11/2011,141.100985
100,Mercedes-B,M-Class,28.976,NaN,Car,35.300,3.2,215.0,111.0,72.2,180.6,4.387,19.0,20.0,2/10/2011,90.495532
106,Nissan,Xterra,54.158,NaN,Car,22.799,3.3,170.0,104.3,70.4,178.0,3.821,19.4,18.0,1/24/2011,69.782944
107,Nissan,Frontier,65.005,NaN,Car,17.890,3.3,170.0,116.1,66.5,196.1,3.217,19.4,18.0,8/27/2011,67.889271
109,Oldsmobile,Intrigue,38.554,NaN,Passenger,24.150,3.5,215.0,109.0,73.6,195.9,3.455,18.0,NaN,4/1/2011,86.272523
110,Oldsmobile,Alero,80.255,NaN,Passenger,18.270,2.4,150.0,107.0,70.1,186.7,2.958,15.0,27.0,10/20/2009,60.727447
117,Plymouth,Prowler,1.872,NaN,Passenger,43.000,3.5,253.0,113.3,76.3,165.4,2.850,12.0,21.0,6/27/2012,106.984456
123,Pontiac,Montana,39.572,NaN,Car,25.635,3.4,185.0,120.0,72.7,201.3,3.942,25.0,23.0,7/22/2012,76.208440
127,Saab,5-Sep,9.191,NaN,Passenger,33.120,2.3,170.0,106.4,70.6,189.2,3.280,18.5,23.0,11/9/2012,73.503778
128,Saab,3-Sep,12.115,NaN,Passenger,26.100,2.0,185.0,102.6,67.4,182.2,2.990,16.9,23.0,6/12/2011,76.023048
132,Saturn,LW,8.472,NaN,Passenger,18.835,2.2,137.0,106.5,69.0,190.4,3.075,13.1,27.0,8/5/2011,56.295243
133,Saturn,LS,49.989,NaN,Passenger,15.010,2.2,137.0,106.5,69.0,190.4,2.910,13.1,28.0,12/4/2012,54.819728
134,Subaru,Outback,47.107,NaN,Passenger,22.695,2.5,165.0,103.5,67.5,185.8,3.415,16.9,25.0,7/7/2011,67.765908
135,Subaru,Forester,33.028,NaN,Car,20.095,2.5,165.0,99.4,68.3,175.2,3.125,15.9,24.0,9/10/2012,66.762943
141,Toyota,Sienna,65.119,NaN,Car,22.368,3.0,194.0,114.2,73.4,193.5,3.759,20.9,22.0,10/5/2012,78.027219
150,Volkswagen,Beetle,49.463,NaN,Passenger,15.900,2.0,115.0,98.9,67.9,161.1,2.769,14.5,26.0,10/20/2011,47.329632
151,Volvo,S40,16.957,NaN,Passenger,23.400,1.9,160.0,100.5,67.6,176.6,2.998,15.8,25.0,2/18/2011,66.113057
152,Volvo,V40,3.545,NaN,Passenger,24.400,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.500,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.800,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.000,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [27]:
dummy = data[subset].fillna(-9999999)
dummy.replace(-9999999, 0)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
7,BMW,323i,19.747,0.0,Passenger,26.990,2.5,170.0,107.3,68.4,176.0,3.179,16.6,26.0,6/28/2011,71.191207
18,Cadillac,Escalade,14.785,0.0,Car,46.225,5.7,255.0,117.5,77.0,201.2,5.572,30.0,15.0,4/17/2012,109.509117
27,Chevrolet,Impala,107.995,0.0,Passenger,18.890,3.4,180.0,110.5,73.0,200.0,3.389,17.0,27.0,6/18/2011,71.838039
34,Chrysler,300M,30.696,0.0,Passenger,29.185,3.5,253.0,113.0,74.4,197.8,3.567,17.0,23.0,2/10/2012,101.655244
44,Dodge,Durango,101.323,0.0,Car,26.310,5.2,230.0,115.7,71.7,193.5,4.394,25.0,17.0,6/27/2012,92.854125
50,Ford,Focus,175.670,0.0,Passenger,12.315,2.0,107.0,103.0,66.9,174.8,2.564,13.2,30.0,7/22/2012,43.117132
66,Jaguar,S-Type,15.467,0.0,Passenger,42.800,3.0,240.0,114.5,71.6,191.3,3.650,18.4,21.0,11/3/2012,102.178985
72,Lexus,GS400,3.334,0.0,Passenger,46.305,4.0,300.0,110.2,70.9,189.2,3.693,19.8,21.0,11/28/2012,125.013357
74,Lexus,LX470,9.126,0.0,Car,60.105,4.7,230.0,112.2,76.4,192.5,5.401,25.4,15.0,10/30/2012,105.760458
75,Lexus,RX300,51.238,0.0,Car,34.605,3.0,220.0,103.0,71.5,180.1,3.900,17.2,21.0,1/4/2012,91.943802
78,Lincoln,Navigator,22.925,0.0,Car,42.660,5.4,300.0,119.0,79.9,204.8,5.393,30.0,15.0,12/23/2012,123.972047
96,Mercedes-B,SLK,7.998,0.0,Passenger,38.900,2.3,190.0,94.5,67.5,157.9,3.055,15.9,26.0,1/16/2011,82.807362
97,Mercedes-B,SLK230,1.526,0.0,Passenger,41.000,2.3,185.0,94.5,67.5,157.3,2.975,14.0,27.0,8/6/2011,81.848969
98,Mercedes-B,CLK Coupe,11.592,0.0,Passenger,41.600,3.2,215.0,105.9,67.8,180.3,3.213,16.4,26.0,7/8/2011,92.925792
99,Mercedes-B,CL500,0.954,0.0,Passenger,85.500,5.0,302.0,113.6,73.1,196.6,4.115,23.2,20.0,4/11/2011,141.100985
100,Mercedes-B,M-Class,28.976,0.0,Car,35.300,3.2,215.0,111.0,72.2,180.6,4.387,19.0,20.0,2/10/2011,90.495532
106,Nissan,Xterra,54.158,0.0,Car,22.799,3.3,170.0,104.3,70.4,178.0,3.821,19.4,18.0,1/24/2011,69.782944
107,Nissan,Frontier,65.005,0.0,Car,17.890,3.3,170.0,116.1,66.5,196.1,3.217,19.4,18.0,8/27/2011,67.889271
109,Oldsmobile,Intrigue,38.554,0.0,Passenger,24.150,3.5,215.0,109.0,73.6,195.9,3.455,18.0,0.0,4/1/2011,86.272523
110,Oldsmobile,Alero,80.255,0.0,Passenger,18.270,2.4,150.0,107.0,70.1,186.7,2.958,15.0,27.0,10/20/2009,60.727447
117,Plymouth,Prowler,1.872,0.0,Passenger,43.000,3.5,253.0,113.3,76.3,165.4,2.850,12.0,21.0,6/27/2012,106.984456
123,Pontiac,Montana,39.572,0.0,Car,25.635,3.4,185.0,120.0,72.7,201.3,3.942,25.0,23.0,7/22/2012,76.208440
127,Saab,5-Sep,9.191,0.0,Passenger,33.120,2.3,170.0,106.4,70.6,189.2,3.280,18.5,23.0,11/9/2012,73.503778
128,Saab,3-Sep,12.115,0.0,Passenger,26.100,2.0,185.0,102.6,67.4,182.2,2.990,16.9,23.0,6/12/2011,76.023048
132,Saturn,LW,8.472,0.0,Passenger,18.835,2.2,137.0,106.5,69.0,190.4,3.075,13.1,27.0,8/5/2011,56.295243
133,Saturn,LS,49.989,0.0,Passenger,15.010,2.2,137.0,106.5,69.0,190.4,2.910,13.1,28.0,12/4/2012,54.819728
134,Subaru,Outback,47.107,0.0,Passenger,22.695,2.5,165.0,103.5,67.5,185.8,3.415,16.9,25.0,7/7/2011,67.765908
135,Subaru,Forester,33.028,0.0,Car,20.095,2.5,165.0,99.4,68.3,175.2,3.125,15.9,24.0,9/10/2012,66.762943
141,Toyota,Sienna,65.119,0.0,Car,22.368,3.0,194.0,114.2,73.4,193.5,3.759,20.9,22.0,10/5/2012,78.027219
150,Volkswagen,Beetle,49.463,0.0,Passenger,15.900,2.0,115.0,98.9,67.9,161.1,2.769,14.5,26.0,10/20/2011,47.329632
151,Volvo,S40,16.957,0.0,Passenger,23.400,1.9,160.0,100.5,67.6,176.6,2.998,15.8,25.0,2/18/2011,66.113057
152,Volvo,V40,3.545,0.0,Passenger,24.400,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,0.0,Passenger,27.500,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,0.0,Passenger,28.800,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,0.0,Passenger,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,0.0,Passenger,36.000,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [31]:
# data.dropna()
data.shape

(157, 16)

In [32]:
fixed_data = data.dropna()

In [33]:
fixed_data

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
5,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Volkswagen,Golf,9.761,11.425,Passenger,14.90,2.0,115.0,98.9,68.3,163.3,2.767,14.5,26.0,1/24/2011,46.943877
146,Volkswagen,Jetta,83.721,13.240,Passenger,16.70,2.0,115.0,98.9,68.3,172.3,2.853,14.5,26.0,8/27/2011,47.638237
147,Volkswagen,Passat,51.102,16.725,Passenger,21.20,1.8,150.0,106.4,68.5,184.1,3.043,16.4,27.0,10/30/2012,61.701381
148,Volkswagen,Cabrio,9.569,16.575,Passenger,19.99,2.0,115.0,97.4,66.7,160.4,3.079,13.7,26.0,5/31/2011,48.907372
149,Volkswagen,GTI,5.596,13.760,Passenger,17.50,2.0,115.0,98.9,68.3,163.3,2.762,14.6,26.0,4/1/2011,47.946841

In [35]:
data['Latest_Launch']

0        2/2/2012
1        6/3/2011
2        1/4/2012
3       3/10/2011
4       10/8/2011
          ...
152     9/21/2011
153    11/24/2012
154     6/25/2011
155     4/26/2011
156    11/14/2011
Name: Latest_Launch, Length: 157, dtype: object

In [37]:
pd.set_option('display.max_rows', 1000)

In [38]:
data['Latest_Launch']

0        2/2/2012
1        6/3/2011
2        1/4/2012
3       3/10/2011
4       10/8/2011
5        8/9/2011
6       2/27/2012
7       6/28/2011
8       1/29/2012
9        4/4/2011
10      11/2/2011
11       9/3/2011
12      3/23/2012
13      7/23/2011
14      2/23/2012
15      4/29/2011
16     11/27/2011
17      9/28/2011
18      4/17/2012
19      8/17/2011
20      3/19/2012
21      5/24/2011
22     12/22/2011
23     10/23/2011
24      5/12/2012
25      9/11/2011
26      4/13/2012
27      6/18/2011
28      1/16/2012
29     11/17/2011
30       6/6/2012
31      10/6/2011
32       5/8/2012
33      7/13/2011
34      2/10/2012
35     12/12/2011
36       7/1/2012
37     10/31/2011
38       6/2/2012
39       8/7/2011
40       3/6/2012
41       1/6/2012
42      7/26/2012
43     11/25/2011
44      6/27/2012
45       9/1/2011
46      3/31/2012
47      1/31/2012
48      8/20/2012
49     12/20/2011
50      7/22/2012
51      9/26/2011
52      4/25/2012
53      2/25/2012
54      9/14/2012
55      1/14/2012
56      8/16/2012
57     10/21/2011
58      5/20/2012
59      3/21/2012
60      10/9/2012
61       2/8/2012
62      9/10/2012
63     11/15/2011
64      6/14/2012
65      4/15/2012
66      11/3/2012
67       3/4/2012
68      10/5/2012
69     12/10/2011
70       7/9/2012
71      5/10/2012
72     11/28/2012
73      3/29/2012
74     10/30/2012
75       1/4/2012
76       8/3/2012
77       6/4/2012
78     12/23/2012
79      4/23/2012
80     11/24/2012
81      1/29/2012
82      8/28/2012
83      6/29/2012
84      1/17/2012
85      5/18/2012
86     12/19/2012
87      2/23/2012
88      9/22/2012
89      7/24/2012
90      2/13/2008
91     10/20/2009
92      4/24/2011
93      7/12/2011
94      6/13/2011
95      3/17/2011
96      1/16/2011
97       8/6/2011
98       7/8/2011
99      4/11/2011
100     2/10/2011
101     8/31/2011
102      8/2/2011
103      5/6/2011
104      3/7/2011
105     9/25/2011
106     1/24/2011
107     8/27/2011
108     5/31/2011
109      4/1/2011
110    10/20/2009
111     2/18/2011
112     9/21/2011
113     6/25/2011
114     4/26/2011
115    11/14/2011
116     4/24/2011
117     6/27/2012
118     1/25/2012
119    11/26/2012
120     6/16/2012
121    10/15/2012
122     5/18/2011
123     7/22/2012
124     2/19/2012
125    12/21/2012
126     7/11/2011
127     11/9/2012
128     6/12/2011
129     8/16/2012
130     3/16/2011
131     1/15/2011
132      8/5/2011
133     12/4/2012
134      7/7/2011
135     9/10/2012
136     4/11/2011
137     2/10/2011
138     8/31/2011
139    12/29/2012
140      8/1/2011
141     10/5/2012
142      5/6/2011
143      3/7/2011
144     9/25/2011
145     1/24/2011
146     8/27/2011
147    10/30/2012
148     5/31/2011
149      4/1/2011
150    10/20/2011
151     2/18/2011
152     9/21/2011
153    11/24/2012
154     6/25/2011
155     4/26/2011
156    11/14/2011
Name: Latest_Launch, dtype: object

In [40]:
# convert string dates into datetime objects 
fixed_dates = pd.to_datetime(data['Latest_Launch'])

In [46]:
# check data types 
fixed_dates.iloc[0]
type(fixed_dates.iloc[0])

pandas._libs.tslibs.timestamps.Timestamp

In [47]:
type(data['Latest_Launch'].iloc[0])

str

In [59]:
# help(fixed_dates.iloc[0])

In [54]:
# access attributes into our datasets. We can view .year, .month, .day, .week, .monthname 
fixed_dates.iloc[0].year

2012

In [57]:
fixed_data['Latest_Launch'] = fixed_dates

<ipython-input-57-6779f4090f36>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fixed_data['Latest_Launch'] = fixed_dates

In [58]:
fixed_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 117 entries, 0 to 149
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         117 non-null    object
 1   Model                117 non-null    object
 2   Sales_in_thousands   117 non-null    float64
 3   __year_resale_value  117 non-null    float64
 4   Vehicle_type         117 non-null    object
 5   Price_in_thousands   117 non-null    float64
 6   Engine_size          117 non-null    float64
 7   Horsepower           117 non-null    float64
 8   Wheelbase            117 non-null    float64
 9   Width                117 non-null    float64
 10  Length               117 non-null    float64
 11  Curb_weight          117 non-null    float64
 12  Fuel_capacity        117 non-null    float64
 13  Fuel_efficiency      117 non-null    float64
 14  Latest_Launch        117 non-null    datetime64[ns]
 15  Power_perf_factor    117 non-null    float64
dtypes: datetime64[ns](1), float64(12), object(3)
memory usage: 15.5+ KB

In [66]:
# identify duplicate model
fixed_data[fixed_data['Model'].duplicated()]

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
114,Plymouth,Neon,32.734,7.75,Passenger,12.64,2.0,132.0,105.0,74.4,174.4,2.559,12.5,29.0,2011-04-26,52.084899

In [67]:
# retreive duplicate model
fixed_data[fixed_data['Model'] == 'Neon']

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
35,Dodge,Neon,76.034,7.75,Passenger,12.64,2.0,132.0,105.0,74.4,174.4,2.567,12.5,29.0,2011-12-12,52.084899
114,Plymouth,Neon,32.734,7.75,Passenger,12.64,2.0,132.0,105.0,74.4,174.4,2.559,12.5,29.0,2011-04-26,52.084899

In [68]:
# we did some googling to figure out whether to keep these values or not.
# we realized that both Dodge and Plymouth are actually the same rebranded company 
# so we decided to remove the older one (Plymouth)

# remove our duplicate model
fixed_data1 = fixed_data.drop(index=[114])

In [70]:
fixed_data1

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2012-02-02,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,2011-06-03,91.370778
3,Acura,RL,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,2011-03-10,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,2011-10-08,62.777639
5,Audi,A6,18.780,23.555,Passenger,33.950,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,2011-08-09,84.565105
6,Audi,A8,1.380,39.000,Passenger,62.000,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0,2012-02-27,134.656858
8,BMW,328i,9.231,28.675,Passenger,33.400,2.8,193.0,107.3,68.5,176.0,3.197,16.6,24.0,2012-01-29,81.877069
9,BMW,528i,17.527,36.125,Passenger,38.900,2.8,193.0,111.4,70.9,188.0,3.472,18.5,25.0,2011-04-04,83.998724
10,Buick,Century,91.561,12.475,Passenger,21.975,3.1,175.0,109.0,72.7,194.6,3.368,17.5,25.0,2011-11-02,71.181451
11,Buick,Regal,39.350,13.740,Passenger,25.300,3.8,240.0,109.0,72.7,196.2,3.543,17.5,23.0,2011-09-03,95.636703
12,Buick,Park Avenue,27.851,20.190,Passenger,31.965,3.8,205.0,113.8,74.7,206.8,3.778,18.5,24.0,2012-03-23,85.828408
13,Buick,LeSabre,83.257,13.360,Passenger,27.885,3.8,205.0,112.2,73.5,200.0,3.591,17.5,25.0,2011-07-23,84.254526
14,Cadillac,DeVille,63.729,22.525,Passenger,39.895,4.6,275.0,115.3,74.5,207.2,3.978,18.5,22.0,2012-02-23,113.854598
16,Cadillac,Eldorado,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,75.5,200.6,3.843,19.0,22.0,2011-11-27,113.765874
17,Cadillac,Catera,11.185,18.225,Passenger,31.010,3.0,200.0,107.4,70.3,194.8,3.770,18.0,22.0,2011-09-28,83.483094
19,Chevrolet,Cavalier,145.519,9.250,Passenger,13.260,2.2,115.0,104.1,67.9,180.9,2.676,14.3,27.0,2011-08-17,46.363347
20,Chevrolet,Malibu,135.126,11.225,Passenger,16.535,3.1,170.0,107.0,69.4,190.4,3.051,15.0,25.0,2012-03-19,67.314462
21,Chevrolet,Lumina,24.629,10.310,Passenger,18.890,3.1,175.0,107.5,72.5,200.9,3.330,16.6,25.0,2011-05-24,69.991396
22,Chevrolet,Monte Carlo,42.593,11.525,Passenger,19.390,3.4,180.0,110.5,72.7,197.9,3.340,17.0,27.0,2011-12-22,72.030917
23,Chevrolet,Camaro,26.402,13.025,Passenger,24.340,3.8,200.0,101.1,74.1,193.2,3.500,16.8,25.0,2011-10-23,81.118543
24,Chevrolet,Corvette,17.947,36.225,Passenger,45.705,5.7,345.0,104.5,73.6,179.7,3.210,19.1,22.0,2012-05-12,141.141150
25,Chevrolet,Prizm,32.299,9.125,Passenger,13.960,1.8,120.0,97.1,66.7,174.3,2.398,13.2,33.0,2011-09-11,48.297636
26,Chevrolet,Metro,21.855,5.160,Passenger,9.235,1.0,55.0,93.1,62.6,149.4,1.895,10.3,45.0,2012-04-13,23.276272
28,Chrysler,Sebring Coupe,7.854,12.360,Passenger,19.840,2.5,163.0,103.7,69.7,190.9,2.967,15.9,24.0,2012-01-16,65.957184
29,Chrysler,Sebring Conv.,32.775,14.180,Passenger,24.495,2.5,168.0,106.0,69.2,193.0,3.332,16.0,24.0,2011-11-17,69.521355
30,Chrysler,Concorde,31.148,13.725,Passenger,22.245,2.7,200.0,113.0,74.4,209.1,3.452,17.0,26.0,2012-06-06,80.023782
31,Chrysler,Cirrus,32.306,12.640,Passenger,16.480,2.0,132.0,108.0,71.0,186.0,2.911,16.0,27.0,2011-10-06,53.566200
32,Chrysler,LHS,13.462,17.325,Passenger,28.340,3.5,253.0,113.0,74.4,207.7,3.564,17.0,23.0,2012-05-08,101.329281
35,Dodge,Neon,76.034,7.750,Passenger,12.640,2.0,132.0,105.0,74.4,174.4,2.567,12.5,29.0,2011-12-12,52.084899
36,Dodge,Avenger,4.734,12.545,Passenger,19.045,2.5,163.0,103.7,69.1,190.2,2.879,15.9,24.0,2012-07-01,65.650508
37,Dodge,Stratus,71.186,10.185,Passenger,20.230,2.5,168.0,108.0,71.0,186.0,3.058,16.0,24.0,2011-10-31,67.876108
39,Dodge,Viper,0.916,58.470,Passenger,69.725,8.0,450.0,96.2,75.7,176.7,3.375,19.0,16.0,2011-08-07,188.144323
40,Dodge,Ram Pickup,227.061,15.060,Car,19.460,5.2,230.0,138.7,79.3,224.2,4.470,26.0,17.0,2012-03-06,90.211700
41,Dodge,Ram Wagon,16.767,15.510,Car,21.315,3.9,175.0,109.6,78.8,192.6,4.245,32.0,15.0,2012-01-06,71.135292
42,Dodge,Ram Van,31.038,13.425,Car,18.575,3.9,175.0,127.2,78.8,208.5,4.298,32.0,16.0,2012-07-26,70.078322
43,Dodge,Dakota,111.313,11.260,Car,16.980,2.5,120.0,131.0,71.5,215.0,3.557,22.0,19.0,2011-11-25,49.645002
45,Dodge,Caravan,181.749,12.025,Car,19.565,2.4,150.0,113.3,76.8,186.3,3.533,20.0,24.0,2011-09-01,61.227000
46,Ford,Escort,70.227,7.425,Passenger,12.070,2.0,110.0,98.4,67.0,174.7,2.468,12.7,30.0,2012-03-31,44.083709
47,Ford,Mustang,113.369,12.760,Passenger,21.560,3.8,190.0,101.3,73.1,183.2,3.203,15.7,24.0,2012-01-31,76.509185
48,Ford,Contour,35.068,8.835,Passenger,17.035,2.5,170.0,106.5,69.1,184.6,2.769,15.0,25.0,2012-08-20,67.351011
49,Ford,Taurus,245.815,10.055,Passenger,17.885,3.0,155.0,108.5,73.0,197.6,3.368,16.0,24.0,2011-12-20,62.503740
51,Ford,Crown Victoria,63.403,14.210,Passenger,22.195,4.6,200.0,114.7,78.2,212.0,3.908,19.0,21.0,2011-09-26,80.499537
52,Ford,Explorer,276.747,16.640,Car,31.930,4.0,210.0,111.6,70.2,190.7,3.876,21.0,19.0,2012-04-25,87.635496
53,Ford,Windstar,155.787,13.175,Car,21.410,3.0,150.0,120.7,76.6,200.9,3.761,26.0,21.0,2012-02-25,62.095048
54,Ford,Expedition,125.338,23.575,Car,36.135,4.6,240.0,119.0,78.7,204.6,4.808,26.0,16.0,2012-09-14,100.024802
55,Ford,Ranger,220.650,7.850,Car,12.050,2.5,119.0,117.5,69.4,200.7,3.086,20.0,23.0,2012-01-14,47.389531
56,Ford,F-Series,540.561,15.075,Car,26.935,4.6,220.0,138.5,79.1,224.5,4.241,25.1,18.0,2012-08-16,89.401935
57,Honda,Civic,199.685,9.850,Passenger,12.885,1.6,106.0,103.2,67.1,175.1,2.339,11.9,32.0,2011-10-21,42.879097
58,Honda,Accord,230.902,13.210,Passenger,15.350,2.3,135.0,106.9,70.3,188.8,2.932,17.1,27.0,2012-05-20,54.269548
59,Honda,CR-V,73.203,17.710,Car,20.550,2.0,146.0,103.2,68.9,177.6,3.219,15.3,24.0,2012-03-21,60.087967
60,Honda,Passport,12.855,17.525,Car,26.600,3.2,205.0,106.4,70.4,178.2,3.857,21.1,19.0,2012-10-09,83.602501
61,Honda,Odyssey,76.029,19.490,Car,26.000,3.5,210.0,118.1,75.6,201.2,4.288,20.0,23.0,2012-02-08,85.217691
62,Hyundai,Accent,41.184,5.860,Passenger,9.699,1.5,92.0,96.1,65.7,166.7,2.240,11.9,31.0,2012-09-10,36.672284
63,Hyundai,Elantra,66.692,7.825,Passenger,11.799,2.0,140.0,100.4,66.9,174.0,2.626,14.5,27.0,2011-11-15,54.590045
64,Hyundai,Sonata,29.450,8.910,Passenger,14.999,2.4,148.0,106.3,71.6,185.4,3.072,17.2,25.0,2012-06-14,58.758249
65,Infiniti,I30,23.713,19.690,Passenger,29.465,3.0,227.0,108.3,70.2,193.7,3.342,18.5,25.0,2012-04-15,92.436889
67,Jeep,Wrangler,55.557,13.475,Car,14.460,2.5,120.0,93.4,66.7,152.0,3.045,19.0,17.0,2012-03-04,48.672898
68,Jeep,Cherokee,80.556,13.775,Car,21.620,4.0,190.0,101.4,69.4,167.5,3.194,20.0,20.0,2012-10-05,76.584440
69,Jeep,Grand Cherokee,157.040,18.810,Car,26.895,4.0,195.0,105.9,72.3,181.5,3.880,20.5,19.0,2011-12-10,80.387779
70,Lexus,ES300,24.072,26.975,Passenger,31.505,3.0,210.0,105.1,70.5,190.2,3.373,18.5,23.0,2012-07-09,87.211001
71,Lexus,GS300,12.698,32.075,Passenger,37.805,3.0,225.0,110.2,70.9,189.2,3.638,19.8,23.0,2012-05-10,94.946698
73,Lexus,LS400,6.375,40.375,Passenger,54.005,4.0,290.0,112.2,72.0,196.7,3.890,22.5,22.0,2012-03-29,124.446716
76,Lincoln,Continental,13.798,20.525,Passenger,39.080,4.6,275.0,109.0,73.6,208.5,3.868,20.0,22.0,2012-08-03,113.540207
77,Lincoln,Town car,48.911,21.725,Passenger,43.330,4.6,215.0,117.7,78.2,215.3,4.121,19.0,21.0,2012-06-04,93.957917
79,Mitsubishi,Mirage,26.232,8.325,Passenger,13.987,1.8,113.0,98.4,66.5,173.6,2.250,13.2,30.0,2012-04-23,45.832181
80,Mitsubishi,Eclipse,42.541,10.395,Passenger,19.047,2.4,154.0,100.8,68.9,175.4,2.910,15.9,24.0,2012-11-24,62.441962
81,Mitsubishi,Galant,55.616,10.595,Passenger,17.357,2.4,145.0,103.7,68.5,187.8,2.945,16.3,25.0,2012-01-29,58.606773
82,Mitsubishi,Diamante,5.711,16.575,Passenger,24.997,3.5,210.0,107.1,70.3,194.1,3.443,19.0,22.0,2012-08-28,84.830779
83,Mitsubishi,3000GT,0.110,20.940,Passenger,25.450,3.0,161.0,97.2,72.4,180.3,3.131,19.8,21.0,2012-06-29,67.544155
84,Mitsubishi,Montero,11.337,19.125,Car,31.807,3.5,200.0,107.3,69.9,186.6,4.520,24.3,18.0,2012-01-17,83.920815
85,Mitsubishi,Montero Sport,39.348,13.880,Car,22.527,3.0,173.0,107.3,66.7,178.3,3.510,19.5,20.0,2012-05-18,70.660942
86,Mercury,Mystique,14.351,8.800,Passenger,16.240,2.0,125.0,106.5,69.1,184.8,2.769,15.0,28.0,2012-12-19,50.997748
87,Mercury,Cougar,26.529,13.890,Passenger,16.540,2.0,125.0,106.4,69.6,185.0,2.892,16.0,30.0,2012-02-23,51.113474
88,Mercury,Sable,67.956,11.030,Passenger,19.035,3.0,153.0,108.5,73.0,199.7,3.379,16.0,24.0,2012-09-22,62.239967
89,Mercury,Grand Marquis,81.174,14.875,Passenger,22.605,4.6,200.0,114.7,78.2,212.0,3.958,19.0,21.0,2012-07-24,80.657696
90,Mercury,Mountaineer,27.609,20.430,Car,27.560,4.0,210.0,111.6,70.2,190.1,3.876,21.0,18.0,2008-02-13,85.949744
91,Mercury,Villager,20.380,14.795,Car,22.510,3.3,170.0,112.2,74.9,194.7,3.944,20.0,21.0,2009-10-20,69.671461
92,Mercedes-B,C-Class,18.392,26.050,Passenger,31.750,2.3,185.0,105.9,67.7,177.4,3.250,16.4,26.0,2011-04-24,78.280731
93,Mercedes-B,E-Class,27.602,41.450,Passenger,49.900,3.2,221.0,111.5,70.8,189.4,3.823,21.1,25.0,2011-07-12,98.249737
94,Mercedes-B,S-Class,16.774,50.375,Passenger,69.700,4.3,275.0,121.5,73.1,203.1,4.133,23.2,21.0,2011-06-13,125.273876
95,Mercedes-B,SL-Class,3.311,58.600,Passenger,82.600,5.0,302.0,99.0,71.3,177.1,4.125,21.1,20.0,2011-03-17,139.982294
101,Nissan,Sentra,42.643,8.450,Passenger,13.499,1.8,126.0,99.8,67.3,177.5,2.593,13.2,30.0,2011-08-31,50.241978
102,Nissan,Altima,88.094,11.295,Passenger,20.390,2.4,155.0,103.1,69.1,183.5,3.012,15.9,25.0,2011-08-02,63.313728
103,Nissan,Maxima,79.853,15.125,Passenger,26.249,3.0,222.0,108.3,70.3,190.5,3.294,18.5,25.0,2011-05-06,89.427820
104,Nissan,Quest,27.308,15.380,Car,26.399,3.3,170.0,112.2,74.9,194.8,3.991,20.0,21.0,2011-03-07,71.171664
105,Nissan,Pathfinder,42.574,17.810,Car,29.299,3.3,170.0,106.3,71.7,182.6,3.947,21.0,19.0,2011-09-25,72.290355
108,Oldsmobile,Cutlass,1.112,11.240,Passenger,18.145,3.1,150.0,107.0,69.4,192.0,3.102,15.2,25.0,2011-05-31,60.861612
111,Oldsmobile,Aurora,14.690,19.890,Passenger,36.229,4.0,250.0,113.8,74.4,205.4,3.967,18.5,22.0,2011-02-18,103.441693
112,Oldsmobile,Bravada,20.017,19.925,Car,31.598,4.3,190.0,107.0,67.8,181.2,4.068,17.5,19.0,2011-09-21,80.511673
113,Oldsmobile,Silhouette,24.361,15.240,Car,25.345,3.4,185.0,120.0,72.2,201.4,3.948,25.0,22.0,2011-06-25,76.096570
115,Plymouth,Breeze,5.240,9.800,Passenger,16.080,2.0,132.0,108.0,71.0,186.3,2.942,16.0,27.0,2011-11-14,53.411898
116,Plymouth,Voyager,24.155,12.025,Car,18.850,2.4,150.0,113.3,76.8,186.3,3.528,20.0,24.0,2011-04-24,60.951185
118,Pontiac,Sunfire,51.645,13.790,Passenger,21.610,2.4,150.0,104.1,68.4,181.9,2.906,15.0,27.0,2012-01-25,62.015870
119,Pontiac,Grand Am,131.097,10.290,Passenger,19.720,3.4,175.0,107.0,70.4,186.3,3.091,15.2,25.0,2012-11-26,70.389737
120,Pontiac,Firebird,19.911,17.805,Passenger,25.310,3.8,200.0,101.1,74.5,193.4,3.492,16.8,25.0,2012-06-16,81.492726
121,Pontiac,Grand Prix,92.364,14.010,Passenger,21.665,3.8,195.0,110.5,72.7,196.5,3.396,18.0,25.0,2012-10-15,78.318168
122,Pontiac,Bonneville,35.945,13.225,Passenger,23.755,3.8,205.0,112.2,72.6,202.5,3.590,17.5,24.0,2011-05-18,82.661356
124,Porsche,Boxter,8.982,41.250,Passenger,41.430,2.7,217.0,95.2,70.1,171.0,2.778,17.0,22.0,2012-02-19,93.437331
125,Porsche,Carrera Coupe,1.280,60.625,Passenger,71.020,3.4,300.0,92.6,69.5,174.5,3.032,17.0,21.0,2012-12-21,134.390975
126,Porsche,Carrera Cabrio,1.866,67.550,Passenger,74.970,3.4,300.0,92.6,69.5,174.5,3.075,17.0,23.0,2011-07-11,135.914710
129,Saturn,SL,80.620,9.200,Passenger,10.685,1.9,100.0,102.4,66.4,176.9,2.332,12.1,33.0,2012-08-16,39.986425
130,Saturn,SC,24.546,10.590,Passenger,12.535,1.9,100.0,102.4,66.4,180.0,2.367,12.1,33.0,2011-03-16,40.700072
131,Saturn,SW,5.223,10.790,Passenger,14.290,1.9,124.0,102.4,66.4,176.9,2.452,12.1,31.0,2011-01-15,49.865774
136,Toyota,Corolla,142.535,10.025,Passenger,13.108,1.8,120.0,97.0,66.7,174.0,2.420,13.2,33.0,2011-04-11,47.968972
137,Toyota,Camry,247.994,13.245,Passenger,17.518,2.2,133.0,105.2,70.1,188.5,2.998,18.5,27.0,2011-02-10,54.372420
138,Toyota,Avalon,63.849,18.140,Passenger,25.545,3.0,210.0,107.1,71.7,191.9,3.417,18.5,26.0,2011-08-31,84.911898
139,Toyota,Celica,33.269,15.445,Passenger,16.875,1.8,140.0,102.4,68.3,170.5,2.425,14.5,31.0,2012-12-29,56.496030
140,Toyota,Tacoma,84.087,9.575,Car,11.528,2.4,142.0,103.3,66.5,178.7,2.580,15.1,23.0,2011-08-01,55.297117
142,Toyota,RAV4,25.106,13.325,Car,16.888,2.0,127.0,94.9,66.7,163.8,2.668,15.3,27.0,2011-05-06,51.955109
143,Toyota,4Runner,68.411,19.425,Car,22.288,2.7,150.0,105.3,66.5,183.3,3.440,18.5,23.0,2011-03-07,62.355577
144,Toyota,Land Cruiser,9.835,34.080,Car,51.728,4.7,230.0,112.2,76.4,192.5,5.115,25.4,15.0,2011-09-25,102.528984
145,Volkswagen,Golf,9.761,11.425,Passenger,14.900,2.0,115.0,98.9,68.3,163.3,2.767,14.5,26.0,2011-01-24,46.943877
146,Volkswagen,Jetta,83.721,13.240,Passenger,16.700,2.0,115.0,98.9,68.3,172.3,2.853,14.5,26.0,2011-08-27,47.638237
147,Volkswagen,Passat,51.102,16.725,Passenger,21.200,1.8,150.0,106.4,68.5,184.1,3.043,16.4,27.0,2012-10-30,61.701381
148,Volkswagen,Cabrio,9.569,16.575,Passenger,19.990,2.0,115.0,97.4,66.7,160.4,3.079,13.7,26.0,2011-05-31,48.907372
149,Volkswagen,GTI,5.596,13.760,Passenger,17.500,2.0,115.0,98.9,68.3,163.3,2.762,14.6,26.0,2011-04-01,47.946841

In [72]:
fixed_data.shape

(117, 16)

In [73]:
fixed_data1.shape

(116, 16)

Groupby function requires:
- The column (categorical variable) to group on
- The column to display (this can be either categorical or numerical)
- The aggregation function (count, min, max, average etc)

In [85]:
# in practice:
temp = fixed_data.groupby('Manufacturer')['Vehicle_type']

In [88]:
# check the index 
temp.count().idxmax()
# check the value
# temp.count().max()

'Ford'